name: Update Regents Park Apartment List

on:
  schedule:
    - cron:  '42 * * * *'    # At minute 42
  push:
    branches: [ main ]


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup CA certificates
        run: ls -la /etc/ssl/certs
        run: curl https://curl.se/ca/cacert.pem > /tmp/cacert.pem
      - name: Build
        run: cargo build --verbose
      - name: Update list
        run: env SSL_CERT_FILE=/tmp/cacert.pem cargo run > apt_list.csv
      - name: Commit apartment list
        run: |
          git config --global user.name 'Qingyao Sun'
          git config --global user.email 'sunqingyao19970825@icloud.com'
          git add -A
          git commit -am "Automated report"
          git push
