name: Update Regents Park Apartment List

on:
  schedule:
    - cron:  '*/30 * * * *'    # At every 30th minute
  push:
    branches: [ main ]


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
            ref: main
      - name: Cache build dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ github.sha }}
      - name: Build
        run: cargo build --verbose
      - name: Checkout apt_list
        uses: actions/checkout@v2
        with:
            ref: apt_list
            path: apt_list
      - name: Fetch latest apartment list
        run: cargo run > apt_list/2b2b.csv
      - name: Commit apartment list to apt_list
        run: |
          cd apt_list
          git config --global user.name 'Qingyao Sun'
          git config --global user.email 'sunqingyao19970825@icloud.com'
          git add -A
          git diff-index --quiet HEAD || git commit -m "Automated report"
          git push
